server:
    port: 8888

spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/tsawlani/spring-cloud-config-in-tolls
            search-paths:
            - station*
